support claude and gemini in vertex ai
songquanpeng/one-api pull request #1621
Opened 2024-07-08 15:36 UTC by vaayne

close #1574 #1491 #1373

我已确认该 PR 已自测通过，相关截图如下：
### UI Settings
<img width="902" alt="SCR-20240708-uenv" src="https://github.com/songquanpeng/one-api/assets/10231735/343e3308-1880-4c4a-a743-89cfe464aab9">

### Gemini Test
<img width="1724" alt="SCR-20240708-udrf" src="https://github.com/songquanpeng/one-api/assets/10231735/f22c164d-e71c-487b-9196-4a910741bf63">

###  Claude Test
<img width="1717" alt="SCR-20240708-udeq" src="https://github.com/songquanpeng/one-api/assets/10231735/15ae2082-2a96-45f1-bfe3-ee1a80e60541">

### Stream test
<img width="1711" alt="SCR-20240708-udkv" src="https://github.com/songquanpeng/one-api/assets/10231735/5f8ca55d-6761-4732-8991-09de772af17c">

2024-07-08 15:40 UTC, vaayne commented
# How to get ADC
https://cloud.google.com/docs/authentication/application-default-credentials

创建 application-default-credentials 的几个步骤
1. 在 Service Account 页面新建 Service Account 
2. 在选择 Role 的时候需要选择 `Vertex AI User` (使用 Vertex AI 的权限) 和 `Service Account Token Creater` （生成 Access Token 的权限，用于 REST API 请求）
3. 新建一个 Key


<img width="778" alt="SCR-20240708-uhjo" src="https://github.com/songquanpeng/one-api/assets/10231735/1d75f45f-fee3-433a-a321-ac745421a01e">

<img width="681" alt="SCR-20240708-uiav" src="https://github.com/songquanpeng/one-api/assets/10231735/e46f5c9c-492b-4cad-9258-69d005aaf8a6">
<img width="784" alt="SCR-20240708-uiki" src="https://github.com/songquanpeng/one-api/assets/10231735/a65f0adc-d980-4012-88bb-44d13e85f3f1">
<img width="749" alt="SCR-20240708-uitz" src="https://github.com/songquanpeng/one-api/assets/10231735/abf6b207-d2dd-4b7d-9f0f-1a49fcb3d9d2">

2024-07-09 06:12 UTC, Laisky commented
补充

- [需要激活 IAM Service Account Credentials API](https://console.cloud.google.com/apis/library/iamcredentials.googleapis.com?project=chat-408106)

2024-07-09 06:13 UTC, Laisky commented
一个小建议，是不是不需要新增 `Google Cloud Application Default Credentials JSON` 字段，而是填入到已有的 `密钥` 字段里？按照目前的代码实现，`密钥` 字段实际上也是闲置的。

2024-07-09 11:32 UTC, vaayne commented
> 一个小建议，是不是不需要新增 `Google Cloud Application Default Credentials JSON` 字段，而是填入到已有的 `密钥` 字段里？按照目前的代码实现，`密钥` 字段实际上也是闲置的。
> 
> BTW，提交的格式也需要改一下

@Laisky 多谢 Review，我是参照项目里面 AWS 的配置来做实现的，放到 API Key 字段也是 OK 的。
请问提交的格式需要怎么更改，抱歉没有看到具体的格式。

2024-07-10 01:06 UTC, Laisky commented
> > 一个小建议，是不是不需要新增 `Google Cloud Application Default Credentials JSON` 字段，而是填入到已有的 `密钥` 字段里？按照目前的代码实现，`密钥` 字段实际上也是闲置的。
> > BTW，提交的格式也需要改一下
> 
> @Laisky 多谢 Review，我是参照项目里面 AWS 的配置来做实现的，放到 API Key 字段也是 OK 的。 请问提交的格式需要怎么更改，抱歉没有看到具体的格式。

我看你格式已经改掉了。

参照 AWS 的话，AWS 的设置页面是把密钥隐藏掉的，我觉得你也可以考虑把密钥隐藏掉。不然这个字段留空但是还提示必填的话，有点误导性。

参考: https://github.com/songquanpeng/one-api/blob/62ac104eedf99b1d5004daae29f36afc47699923/web/default/src/pages/Channel/EditChannel.js#L509

![CleanShot 2024-07-10 at 09 03 25@2x](https://github.com/songquanpeng/one-api/assets/4532436/6b9e24a2-625d-45af-b298-be9b2158f4a2)

2024-07-10 14:27 UTC, vaayne commented
> > > 一个小建议，是不是不需要新增 `Google Cloud Application Default Credentials JSON` 字段，而是填入到已有的 `密钥` 字段里？按照目前的代码实现，`密钥` 字段实际上也是闲置的。
> > > BTW，提交的格式也需要改一下
> > 
> > 
> > @Laisky 多谢 Review，我是参照项目里面 AWS 的配置来做实现的，放到 API Key 字段也是 OK 的。 请问提交的格式需要怎么更改，抱歉没有看到具体的格式。
> 
> 我看你格式已经改掉了。
> 
> 参照 AWS 的话，AWS 的设置页面是把密钥隐藏掉的，我觉得你也可以考虑把密钥隐藏掉。不然这个字段留空但是还提示必填的话，有点误导性。
> 
> 参考:
> 
> https://github.com/songquanpeng/one-api/blob/62ac104eedf99b1d5004daae29f36afc47699923/web/default/src/pages/Channel/EditChannel.js#L509
> 
> ![CleanShot 2024-07-10 at 09 03 25@2x](https://private-user-images.githubusercontent.com/4532436/347211623-6b9e24a2-625d-45af-b298-be9b2158f4a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjA4MzksIm5iZiI6MTcyMDYyMDUzOSwicGF0aCI6Ii80NTMyNDM2LzM0NzIxMTYyMy02YjllMjRhMi02MjVkLTQ1YWYtYjI5OC1iZTliMjE1OGY0YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTQwODU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTFmOGM2MTFiYzhjOGM3YTg5YWYyNjgxMjE1NTUxMDQyNWQzZmM4ZGNkMTk5NWQ2MDMxZGQ0OTc0ZGY4ZTUyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.glG6HEWEgj5nMu4LTuXNY7NaCNYGpzT27t_PLapgyPY)

很奇怪，我的截图里面使用的是 `berry` 它是没有 api key 这个字段显示的，但是我刚刚用 `default` 的主题试了一下是有这个字段显示的，而且我也没有弄明白是怎么显示的 😅

2024-07-10 14:48 UTC, vaayne commented
> > > 一个小建议，是不是不需要新增 `Google Cloud Application Default Credentials JSON` 字段，而是填入到已有的 `密钥` 字段里？按照目前的代码实现，`密钥` 字段实际上也是闲置的。
> > > BTW，提交的格式也需要改一下
> > 
> > 
> > @Laisky 多谢 Review，我是参照项目里面 AWS 的配置来做实现的，放到 API Key 字段也是 OK 的。 请问提交的格式需要怎么更改，抱歉没有看到具体的格式。
> 
> 我看你格式已经改掉了。
> 
> 参照 AWS 的话，AWS 的设置页面是把密钥隐藏掉的，我觉得你也可以考虑把密钥隐藏掉。不然这个字段留空但是还提示必填的话，有点误导性。
> 
> 参考:
> 
> https://github.com/songquanpeng/one-api/blob/62ac104eedf99b1d5004daae29f36afc47699923/web/default/src/pages/Channel/EditChannel.js#L509
> 
> ![CleanShot 2024-07-10 at 09 03 25@2x](https://private-user-images.githubusercontent.com/4532436/347211623-6b9e24a2-625d-45af-b298-be9b2158f4a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjMyMDEsIm5iZiI6MTcyMDYyMjkwMSwicGF0aCI6Ii80NTMyNDM2LzM0NzIxMTYyMy02YjllMjRhMi02MjVkLTQ1YWYtYjI5OC1iZTliMjE1OGY0YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTQ0ODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDVlMjY5ZmVlM2I2MzhlYjVmNmZkYmZhNTI3YjhkMTE4YjE1YWYzNDViMzlmMGMyYWQ0ZWU3ZWJhN2EzNGZkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EYgxygpLbmNPnyTMSz0SXAYfgtNsWuTqooS0TGJTLbM)

It's done, Thanks @Laisky .

2024-07-10 14:56 UTC, Laisky submitted a review, later dismissed
LGTM

2024-07-11 12:28 UTC, MartialBE approved these changes

2024-07-11 17:30 UTC, MartialBE requested changes

2024-07-11 17:30 UTC, MartialBE commented on relay/adaptor/vertexai/token.go
> +	if token, found := Cache.Get(cacheKey); found {
这里应该需要携带 渠道ID 组成 cacheKey,否则 当有不同渠道帐号时，这里获取到的token是上次请求的。

2024-07-12 05:35 UTC, vaayne commented on relay/adaptor/vertexai/token.go
> +	if token, found := Cache.Get(cacheKey); found {
Thanks @MartialBE
Updated

2024-07-12 05:41 UTC, MartialBE approved these changes

2024-07-12 05:47 UTC, Laisky approved these changes

2024-07-12 15:10 UTC, manjieqi commented
太好了，不用另外搭建转发了。就是Vertex Al Project ID字段其实在json文件里有

2024-07-13 06:58 UTC, songquanpeng commented
很奇怪按理说两个approve可以直接合并的

2024-07-13 06:59 UTC, merged

2024-07-16 08:57 UTC, qingfengmy commented
请问这个大概什么时候发布？

2024-07-17 10:43 UTC, IAn2018cs commented
为什么点击提交按钮没有反应
<img width="864" alt="image" src="https://github.com/user-attachments/assets/8d9e3265-bc05-4e9f-b5f5-4f5b03e438de">

2024-07-18 01:01 UTC, vaayne commented
> 为什么点击提交按钮没有反应
> 
> <img width="864" alt="image" src="https://github.com/user-attachments/assets/8d9e3265-bc05-4e9f-b5f5-4f5b03e438de">
> 
> 

我也发现这个问题了，请先保存为其它的类型例如 OpenAI ，然后修改再保存就没问题了

2024-07-20 16:22 UTC, xkatld commented
> 请问这个大概什么时候发布？

[可以用我打包的](https://github.com/xkatld/one-api-new)

2024-07-22 11:46 UTC, xkatld commented
![image](https://github.com/user-attachments/assets/c20e8f7b-b370-4119-afd8-b8de5bbcba1b)
测试所有预设claude-3*报404
![image](https://github.com/user-attachments/assets/9eb1db93-1005-4260-afc7-74594d774a90)
gemini正常

2024-07-22 11:49 UTC, xkatld commented
这应该是开通claude-3.5了吧
![image](https://github.com/user-attachments/assets/ac2e59af-af8b-4e8a-a254-79622296ad0b)

2024-07-23 01:08 UTC, Laisky commented
> 这应该是开通claude-3.5了吧 ![image](https://private-user-images.githubusercontent.com/36999228/350953699-ac2e59af-af8b-4e8a-a254-79622296ad0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTcxMTksIm5iZiI6MTcyMTY5NjgxOSwicGF0aCI6Ii8zNjk5OTIyOC8zNTA5NTM2OTktYWMyZTU5YWYtYWY4Yi00ZThhLWEyNTQtNzk2MjIyOTZhZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAxMDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzY2I3MmVmMjRlODE2M2IzYTEzMzk2MmYxZDhhZDRjNDU1ZmY1NmI5MDQ4OGUxYjJhNjk1MjcwNDQ1MzI0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTdA0iY7I4zu2esJ6almmr2ZuAj4KbypVghCAsqZqNg)

这代码应该没问题，我在我自己的分支上已经用了很久了。

GCP 的逻辑很复杂，你需要做对四件事

1. 在 model farm 开启模型
2. 正确设置 service account
3. [需要激活 IAM Service Account Credentials API](https://console.cloud.google.com/apis/library/iamcredentials.googleapis.com?project=chat-408106)
4. 设置正确的 region（不是所有的 region 都有 claude 的全部模型！）

2024-07-23 01:13 UTC, manjieqi commented
大佬，vertex的代理现在能用吗？设置好，测试提示504，代理那边没有访问的日志

![image](https://github.com/user-attachments/assets/c266b826-a399-4476-a726-720ac6ea9e01)

2024-07-23 09:59 UTC, KevinSpringer1 commented
![image](https://github.com/user-attachments/assets/d2f25e55-9854-4d5c-b879-e110b062b014)
请求claude的路径不对

2024-07-23 10:00 UTC, KevinSpringer1 commented
publishers/anthropic/models/claude-3-5-sonnet
正确路径如上

2024-07-23 10:02 UTC, vaayne commented
@KevinSpringer1 是你的 Region 不对，现在 Claude 好像只是在 `"europe-west1" or "us-east5"`  这两个区域有。

2024-07-23 10:09 UTC, manjieqi commented
就是渠道里面的代理那里填了一个链接，因为是国内的服务器，所以在国外设置了一个nginx，渠道那里就按要求填的us-east5，请求好像没发到nginx，所以问一下渠道里面的代理能不能用的

2024-07-23 10:14 UTC, vaayne commented
> 就是渠道里面的代理那里填了一个链接，因为是国内的服务器，所以在国外设置了一个nginx，渠道那里就按要求填的us-east5，请求好像没发到nginx，所以问一下渠道里面的代理能不能用的

不知道 Nginx 能不能，我用 Cloudflare 的 AI Gateway 是可以的

2024-07-23 10:26 UTC, manjieqi commented
![image](https://github.com/user-attachments/assets/ce0e5026-376e-41dc-944d-fe5e8daef646)

奇怪，cloudflare也没收到请求，是docker amd64的v0.6.8-alpha.6

2024-07-25 04:53 UTC, skyfollowsnow commented
错误：status code 403: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/moonlit-web-429810-g4/locations/us-central1/publishers/google/models/gemini-1.5-pro-001' (or it may not exist).

请问这个是什么原因：

![image](https://github.com/user-attachments/assets/9a04c1c6-a38a-4850-936f-a80ce77081b9)



确认IAM账号有权限
![image](https://github.com/user-attachments/assets/5ccc0228-41f6-4ad7-b499-27bf174a1b0d)

模型确认该项目开通了。

API也确认开通过

2024-07-25 05:14 UTC, vaayne commented
> 错误：status code 403: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/moonlit-web-429810-g4/locations/us-central1/publishers/google/models/gemini-1.5-pro-001' (or it may not exist).
> 
> 
> 
> 请问这个是什么原因：
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/9a04c1c6-a38a-4850-936f-a80ce77081b9)
> 
> 
> 
> 
> 
> 
> 
> 确认IAM账号有权限
> 
> ![image](https://github.com/user-attachments/assets/5ccc0228-41f6-4ad7-b499-27bf174a1b0d)
> 
> 
> 
> 模型确认该项目开通了。
> 
> 
> 
> API也确认开通过

https://github.com/songquanpeng/one-api/pull/1621#issuecomment-2244783938

应该是 region 问题

2024-07-25 08:40 UTC, skyfollowsnow commented
> > 错误：status code 403: Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/moonlit-web-429810-g4/locations/us-central1/publishers/google/models/gemini-1.5-pro-001' (or it may not exist).
> > 请问这个是什么原因：
> > ![image](https://private-user-images.githubusercontent.com/173973958/351968303-9a04c1c6-a38a-4850-936f-a80ce77081b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTY5NjIsIm5iZiI6MTcyMTg5NjY2MiwicGF0aCI6Ii8xNzM5NzM5NTgvMzUxOTY4MzAzLTlhMDRjMWM2LWEzOGEtNDg1MC05MzZmLWE4MGNlNzcwODFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwODM3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjdjMjhkODQ0Mjg2YzllNTlmOGIwNTMxMjk3MTQyODQ5MjI4NzkxZTJiOWVmMjU3ODEyZjcxNjIyZTdmODg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PDZLg9VvG-20YQhvy5A1AYTnAv0ruMKuInq0AaHfrSg)
> > 确认IAM账号有权限
> > ![image](https://private-user-images.githubusercontent.com/173973958/351968085-5ccc0228-41f6-4ad7-b499-27bf174a1b0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTY5NjIsIm5iZiI6MTcyMTg5NjY2MiwicGF0aCI6Ii8xNzM5NzM5NTgvMzUxOTY4MDg1LTVjY2MwMjI4LTQxZjYtNGFkNy1iNDk5LTI3YmYxNzRhMWIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwODM3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGQ4OGU0ZTI3YzcyZjJiNzBkYmM2ZGEyNDNkY2Y4OWM2ZDViYTJlYTUzOGJiOTc4NWVhYWJmYmZmNWRkOWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PDNI4pr2vhgE5TjwIyzS7Z3imN0bBFd9PRIU77eImho)
> > 模型确认该项目开通了。
> > API也确认开通过
> 
> [#1621 (comment)](https://github.com/songquanpeng/one-api/pull/1621#issuecomment-2244783938)
> 
> 应该是 region 问题

确实是region 问题，如果一个不行，就多换几个做尝试。google云的region 让人很迷惑。

建议role的权限同时给    vertex ai user     和   vertex ai administrator  这两个权限，更加稳妥一些。我之前翻问题的可能性时。找到了这个答案。然后都给了。然后再尝试切换region     成功了。

2024-08-03 01:50 UTC, ivanberry commented
> > 就是渠道里面的代理那里填了一个链接，因为是国内的服务器，所以在国外设置了一个nginx，渠道那里就按要求填的us-east5，请求好像没发到nginx，所以问一下渠道里面的代理能不能用的
> 
> 不知道 Nginx 能不能，我用 Cloudflare 的 AI Gateway 是可以的

您好，我通过CF work自定义域名时会超时（one api机器在国内），但是通过自定义域名时却提示
type authentication_error, code \u003cnil\u003e, message invalid x-api-key。

不走oneapi 直接使用是OK的，通过lobe web 测试通过

2024-08-10 22:34 UTC, yilunzhao commented
@vaayne 大佬请求支持 model garden 里面的其他模型，比如Llama3.1 和Mistral-Large

2024-09-08 01:19 UTC, billowssun commented
按照方法一比一设置，还得隔一段时间才能生效，很容易在这上面瞎折腾
主要注意以下几点：
 1. 创建用户时给权限`Vertex Al User`和`Service Account Token Creator`
 2. 开启各种API，要使用的大模型API（console.cloud.google-vertex ai-模型库）和`IAM Service Account Credentials API`
 3. 区域选择`us-east5`，其他没测试过，很多地区大部分模型不支持，有的支持`claude-3-haiku`
 4. 就算你正确设置了，还要过段时间才能生效

2024-09-26 17:07 UTC, jackchen75 commented
hello,
![image](https://github.com/user-attachments/assets/89c72e72-abca-424c-93ac-15d0ffdafbc2)
查询配额是无限制,大佬指点下，咋回事？

2024-12-25 14:51 UTC, cloudtrekcn commented
求助！！！按照大神的教程，一步一步配置完成，总是报：adaptor not found 的错误，请问是什么情况？

2025-06-06 13:30 UTC, sfvsfv commented
这个功能还没有合并进去吗，现在还是报错adaptor not found 
![image](https://github.com/user-attachments/assets/5f4a051d-47c4-4373-9cf2-23e71b42e115)
![image](https://github.com/user-attachments/assets/a110e561-d02c-4d00-9ee3-564c4c64a1fd)

2025-06-06 14:04 UTC, Laisky commented
@sfvsfv 建议用 https://github.com/Laisky/one-api

2025-07-29 17:01 UTC, SbinFZ commented
> 1. Service Account Token Creator

+1