"add parser multipart/form-data"
songquanpeng/one-api pull request #1690
Opened 2024-07-24 07:44 UTC by bearslyricattack

close #issue1655

我已确认该 PR 已自测通过，相关截图如下：
![QQ20240724-154225](https://github.com/user-attachments/assets/5cf60fb8-1fcb-49a9-a79a-50ce295922e7)

2024-07-24 08:17 UTC, c121914yu submitted a review, later dismissed

2024-07-24 14:11 UTC, sdytzjp commented
没看明白 啥意思  需要怎么做

2024-07-24 14:15 UTC, bearslyricattack commented
> 没看懂啥意思 需要怎么做

就是这个问题的出现是代码本身的问题 原先的代码不能解析multipart/form-data类型的数据 现在可以解析了 使用最新版代码构建就不会有这个问题了

2024-07-24 14:21 UTC, sdytzjp commented
之前升级oneapi0.4.8后fastgpt有问题&nbsp; 退了0.4.7
现在升级到最新版了？



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 24, 2024 22:16 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [songquanpeng/one-api] "add parser multipart/form-data" (PR#1690)




  
没看懂啥意思 需要怎么做
  
就是这个问题的出现是代码本身的问题 原先的代码不能解析multipart/form-data类型的数据 现在可以解析了 使用最新版代码构建就不会有这个问题了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2024-07-24 14:25 UTC, bearslyricattack commented
> 另外 升级后就可以对接第三方语音模型了吗&nbsp; config和oneapi如何配置对接其他语音模型
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Jul 24, 2024 22:16 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [songquanpeng/one-api] "add parser multipart/form-data" (PR#1690) 没看懂啥意思 需要怎么做 就是这个问题的出现是代码本身的问题 原先的代码不能解析multipart/form-data类型的数据 现在可以解析了 使用最新版代码构建就不会有这个问题了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

这个应该还是不行 这次就解决这一个问题

2024-07-26 05:05 UTC, MartialBE requested changes

2024-07-26 05:05 UTC, MartialBE commented on common/gin.go
>  func UnmarshalBodyReusable(c *gin.Context, v any) error {
为什么不直接使用ShouldBind，可以直接判断请求类型来去解析，这里解析成ModelRequest再转成json再由json解析成传入参数，没有必要。

2024-09-22 09:32 UTC, merged

2024-09-22 09:32 UTC, songquanpeng commented
Thx~

2024-10-12 11:03 UTC, William-715 commented
![image](https://github.com/user-attachments/assets/0ba43452-a1e3-4118-bd96-7768e07717ad)
容器升级到最新版本，还是存在去找whisper-1模型，我实际配置的是：	whisper-large-v3模型

2024-10-12 11:05 UTC, William-715 commented
引起whisper-1问题的部分代码更新是还没合并到 v0.6.9-alpha.2容器版本里面吗？