修复了smtp office365 server不可用的问题。
songquanpeng/one-api pull request #334
Opened 2023-07-28 17:00 UTC by thinker007

参考：https://github.com/absentbird/loginauth

让office365的邮箱可以正常发信。

server   := "smtp.office365.com:587"
sender   := "example1@example.com"
password := "hunter2"
subject  := "Test"
message  := "Hello world."
receiver := []string{"example2@example.com"}

auth := loginauth.Auth(sender, password)

body := []byte("Subject:"+subject+"\r\n\r\n"+message)
err := smtp.SendMail(server, auth, sender, receiver, body)
if err != nil {
    log.Fatal(err)
}
log.Println("Email sent successfully.")

2023-07-29 05:01 UTC, songquanpeng commented
原本的兼容么？测试了么

2023-07-29 16:56 UTC, thinker007 commented
> 原本的兼容么？测试了么

测试和原本的完全兼容没有问题

2023-07-30 04:53 UTC, songquanpeng commented on common/email.go
> +		conn, err := net.Dial("tcp", "smtp.office365.com:587")
硬编码？

2023-07-30 04:54 UTC, songquanpeng requested changes

2023-07-30 04:54 UTC, songquanpeng commented on common/email.go
> +		conn, err := net.Dial("tcp", "smtp.office365.com:587")
我严重怀疑你并没有测试过，如果贸然合入将导致大量线上服务无法发送邮件，此 PR 需要更多验证

2023-07-30 14:21 UTC, thinker007 commented
硬编码去除

2023-07-30 14:24 UTC, songquanpeng commented
Okay，估计只能等下个周末有时间处理了

2023-09-17 13:32 UTC, songquanpeng commented
这个 PR 先关了哈，我打算之后把邮件发送独立成一个库

2023-09-17 13:32 UTC, closed without merging