Update misc.go
songquanpeng/one-api pull request #336
Opened 2023-07-29 12:22 UTC by VMCoud

Restrict email registration

2023-07-29 14:06 UTC, songquanpeng requested changes

2023-07-29 14:06 UTC, songquanpeng commented on controller/misc.go
> +        "@163.com", "@qq.com", "@126.com", "@139.com", "@sina.com",
这种硬编码是不行的

2023-07-30 02:47 UTC, VMCoud commented on controller/misc.go
> +        "@163.com", "@qq.com", "@126.com", "@139.com", "@sina.com",
过于复杂需要动好几个文件整不了，大佬有空能加上限制邮箱后缀注册吗，可以防止别人临时邮箱刷邀请

2023-07-30 03:47 UTC, ckt1031 commented on controller/misc.go
> +        "@163.com", "@qq.com", "@126.com", "@139.com", "@sina.com",
> 过于复杂需要动好几个文件整不了，大佬有空能加上限制邮箱后缀注册吗，可以防止别人临时邮箱刷邀请

https://github.com/songquanpeng/one-api/pull/337

2023-07-30 04:14 UTC, songquanpeng commented
#338 正在处理这个问题，所以先关了

2023-07-30 04:14 UTC, closed without merging